#!/usr/bin/env sh

timestamp=$(date +"%Y-%m-%dT%H:%M:%S")

for db in $POSTGRES_DATABASE; do
  echo
  echo "Creating backup: [$db] database..."
  echo
  local_file=$(dump-one-db $db $timestamp)
  echo $local_file
done

exit
