#!/usr/bin/env sh

miniohost=${S3_ENDPOINT}
while true;
  do wget -qO - $miniohost 2>&1 | grep -q "HTTP" && break;
  sleep 1;
done;

if [ -e "${MINIO_ACCESS_KEY_FILE}" ]; then
  MINIO_ROOT_USER=$(cat ${MINIO_ACCESS_KEY_FILE})
elif [ -n "${AWS_ACCESS_KEY_ID}" ]; then
  MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
elif [ -n "${S3_ACCESS_KEY_ID}" ]; then
  MINIO_ROOT_USER=${S3_ACCESS_KEY_ID}
fi

if [ -e "${MINIO_SECRET_KEY_FILE}" ]; then
  MINIO_ROOT_PASSWORD=$(cat ${MINIO_SECRET_KEY_FILE})
elif [ -n "${AWS_SECRET_ACCESS_KEY}" ]; then
  MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
elif [ -n "${S3_SECRET_ACCESS_KEY}" ]; then
  MINIO_ROOT_PASSWORD=${S3_SECRET_ACCESS_KEY}
fi

mcli alias set myminio $miniohost $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;

if [ $# -gt 0 ]; then
  cli="mcli $@"
  echo $cli
  sh -c "$cli"
fi
