#!/usr/bin/env sh

input=$1

for db in $POSTGRES_DATABASE; do
  echo "Restore backup: [$db] database..."
  echo
  PGPASSWORD=${POSTGRES_PASSWORD} -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -tc "SELECT 1 FROM pg_database WHERE datname = '${db}'" | \
    grep -q 1 || PGPASSWORD=${POSTGRES_PASSWORD} createdb -h ${POSTGRES_HOST} -U ${POSTGRES_USER} ${db} 
  PGPASSWORD=${POSTGRES_PASSWORD} pg_restore -v -O -Fc \
    -h $POSTGRES_HOST \
    -p $POSTGRES_PORT \
    -U $POSTGRES_USER \
    $PGRESTORE_EXTRA_OPTS --clean --if-exists \
    -d ${db} $input/backup_${db}.dump
done
