#!/usr/bin/env sh

input=$1

for db in $POSTGRES_DATABASE; do
  echo "Restore backup: [$db] database..."
  echo
  PGPASSWORD=${POSTGRES_PASSWORD} pg_restore -v --create -O -Fc \
    -h $POSTGRES_HOST \
    -p $POSTGRES_PORT \
    -U $POSTGRES_USER \
    $PGRESTORE_EXTRA_OPTS --clean --if-exists \
    -d ${db} $input/backup_${db}.dump
done
